version: '3.7'
services:
  dynamodb:
    command: -jar DynamoDBLocal.jar -dbPath /var/tmp/ -optimizeDbBeforeStartup
    env_file: .env
    image: amazon/dynamodb-local
    ports:
    - 8000:8000
    restart: always
    volumes:
    - dynamodb:/var/tmp/
  localstack:
    image: localstack/localstack
    environment:
      SERVICES: dynamodb,apigateway,lambda,s3
      PORT_WEB_UI: "9000"
    ports:
    - "4567-4584:4567-4584"
    - "9000:9000"
    volumes:
    - localstack:/tmp/localstack
volumes:
  dynamodb:
  localstack:
