version: '3.7'
services:
  dynamodb:
    command: -jar DynamoDBLocal.jar -dbPath /var/tmp/ -optimizeDbBeforeStartup
    env_file: .env
    image: amazon/dynamodb-local
    ports:
    - 8000:8000
    restart: always
    volumes:
    - dynamodb:/var/tmp/
  dynamodb-localstack:
    image: localstack/localstack
    environment:
      SERVICES: dynamodb
    ports:
    - 4569:4569
    - 4570:4570
volumes:
  dynamodb:
